### PR TITLE
Initial PR on v1alpha2 migration (inc. #111)

### PR DESCRIPTION
**Pull request by maelk**
This PR keeps track of the on-going development of v1alpha2. Commits are being added to the v1alpha2 branch in Nordix repository.

### CODE REVIEW

**Comment by russellb** [comment]
/approve

I've agreed to quickly approve v1alpha2 branch changes so the people working on this can quickly iterate and collaborate in this repo.  I'll leave the `/lgtm` to someone closer to the changes.

**Comment by russellb** [comment]
/lgtm

just helping push this one in, we'll still work on how to improve our workflow for this branch so it's not all blocked on me ...

**Comment by mhrivnak** [comment]
I have a review in-progress on #111 . Should I move those comments over here? Should that PR be closed?

**Comment by maelk** [comment]
@mhrivnak yes, we have discussed with @jbrette and @russellb to merge this PR instead. however, it is a work in progress, as some pieces are missing and others are hackish or wrong (for example image tags, registry etc.). You can also complete your code review on #111 and I'll fix it here if it is ok for you.

**Comment by russellb** [comment]
@mhrivnak just FYI in case you didn't catch it - the PR is against the v1alpha2 branch and not master, where the work for v1alpha2 will be done.  I was expecting to do more in depth review when it's time to merge to master.  If you have a chance to provide some feedback along the way, that's great too!

**Comment by russellb** [comment]
@maelk btw, it looks like prow is honoring the OWNERS file in the branch, since it didn't let me approve.  I'll have to manually merge the first PR that adds the OWNERS file.  Since @mhrivnak had some feedback pending, I'll hold off.

**Comment by mhrivnak** [comment]
Great. I just did a high-level review and submitted it on #111.

**Pull request merged**
