### PR TITLE
Fix broken deployment example and update kustomize

### PR DESCRIPTION
**Pull request by maelk**
The deployment example for the cluster was broken when modifying the API, fixing it and updating kustomize

### CODE REVIEW

**Comment by maelk** [comment]
I'll add the missing scripts to run the tests

**Comment by maelk** [comment]
I will fix the linting errors

**Comment by russellb** [comment]
Instead of the new commit to add the scripts you could have merged master into this branch. We will have to deal with any branch conflicts eventually either way.

**Pull request merged**
